name: docker release

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true
      PRERELEASE:
        description: 'Whether this is a prerelease'
        type: boolean
        required: true

  release:
    types: [published]

permissions:
  packages: write
  contents: write
  id-token: write

env:
  TAG_NAME: ad-latest
  IS_PRERELEASE: false

jobs:
  # This workaround is needed, as it's not possible to reference env.FOOBAR directly at this stage
  # - for ex. https://github.com/actions/runner/issues/1189
  release-container-prereq:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-param.outputs.tag }}
      tag_latest: ${{ steps.release-param.outputs.tag_latest }}
    steps:
    - id: release-param
      run: |
        # If env.IS_PRERELEASE is true, set tag to alpha and do not enable tag_latest
        # If env.IS_PRERELEASE is not true (aka false), don't set an extra tag and enable tag_latest
        echo "tag=${{ env.IS_PRERELEASE == 'true' && 'alpha' }}" >> $GITHUB_OUTPUT
        echo "tag_latest=${{ env.IS_PRERELEASE == 'true' && 'false' || 'true' }}" >> $GITHUB_OUTPUT

  release-container:
    needs: release-container-prereq
    uses: ./.github/workflows/reusable-container-workflow.yaml
    with:
      build_type: prod
      tag: ${{ needs.release-container-prereq.outputs.tag }}
      tag_latest: ${{ needs.release-container-prereq.outputs.tag_latest == 'true' }}
      image: ghcr.io/${{ github.repository }}
      registry: ghcr.io
      registry_username: ${{ github.repository_owner }}
      fetch_release: true
      release_version: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [release-container-prereq, release-container]
    runs-on: ubuntu-latest
    steps:
    - name: print_env
      run: env

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5

    - name: Configure Git
      if: env.IS_PRERELEASE != 'true'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: GitHub Push
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.DRAGONFLY_TOKEN }}
        branch: main

    - name: Re-build Docs
      if: env.IS_PRERELEASE != 'true'
      run: |
        curl -s -X POST '${{ secrets.VERCEL_DOCS_WEBHOOK }}'
